#!/bin/sh -e
set -x

autoflake --remove-all-unused-imports --recursive --remove-unused-variables --in-place accentnotifications tests --exclude=__init__.py
black accentnotifications tests
isort accentnotifications tests